---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: singularr-app-secrets
  namespace: singularr
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.singularr-app"
