---
apiVersion: v1
kind: Service
metadata:
  name: singularr-app
spec:
  selector:
    app: singularr-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: singularr-app
spec:
  hosts:
    - singularr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: singularr-app.singularr.svc.cluster.local
            port:
              number: 8080
