---
apiVersion: v1
kind: Service
metadata:
  name: singularr-app
spec:
  selector:
    app: singularr-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: singularr-app
spec:
  hosts:
    - singularr.app
    - www.singularr.app
  gateways:
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - match:
        - authority:
            exact: www.singularr.app
      redirect:
        authority: singularr.app
        redirectCode: 301
    - route:
        - destination:
            host: singularr-app.singularr.svc.cluster.local
            port:
              number: 8080
