---
apiVersion: v1
kind: Service
metadata:
  name: agent-canvas
spec:
  selector:
    app: agent-canvas
  ports:
    - port: 8002
      targetPort: http-public
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: agent-canvas
spec:
  hosts:
    - agents.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: agent-canvas.default.svc.cluster.local
            port:
              number: 8002
