---
- name: Create Semaphore directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ semaphore_compose_dir }}"
      owner: root
      group: root
      mode: "0755"
    - path: "{{ semaphore_data_dir }}"
      owner: "1001"
      group: "1001"
      mode: "0750"

- name: Inject Semaphore secrets
  ansible.builtin.command:
    cmd: "op inject -i {{ role_path }}/templates/.env.tpl"
  register: semaphore_env
  delegate_to: localhost
  become: false
  changed_when: false
  no_log: true

- name: Create Semaphore environment file
  ansible.builtin.copy:
    content: "{{ semaphore_env.stdout }}"
    dest: "{{ semaphore_compose_dir }}/.env"
    owner: root
    group: root
    mode: "0600"
  no_log: true

- name: Copy Semaphore Compose file
  ansible.builtin.copy:
    src: compose.yaml
    dest: "{{ semaphore_compose_dir }}/compose.yaml"
    owner: root
    group: root
    mode: "0644"

- name: Start Semaphore
  community.docker.docker_compose_v2:
    project_src: "{{ semaphore_compose_dir }}"
    state: present
    pull: always
