---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  hosts:
    - "vm.hydrahmlb.cc"
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /select/0/
      route:
        - destination:
            host: vmselect-vmcluster.monitoring.svc.cluster.local
            port:
              number: 8481
