networks:
  application:
    name: nextcloud
  proxy:
    name: proxy
    external: true

services:
  nextcloud-db:
    container_name: nextcloud-db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /share/docker/nextcloud/db:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - application
  nextcloud-dsp:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: nextcloud-dsp
    environment:
      - CONTAINERS=1
      - POST=1
      - DELETE=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - INFO=1
      - VERSION=1
      - EXEC=1
      - BUILD=0
      - SWARM=0
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - application
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:31.0.12-previous
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /share/docker/nextcloud/config:/config
      - /srv/mergerfs/union_01/nextcloud/data:/data
    restart: unless-stopped
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-secure"
      - "traefik.http.middlewares.nextcloud-secure.headers.hostsProxyHeaders=X-Forwarded-Host"
      - "traefik.http.middlewares.nextcloud-secure.headers.referrerPolicy=same-origin"
