---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
  labels:
    app: kiwix
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kiwix
  template:
    metadata:
      labels:
        app: kiwix
    spec:
      securityContext:
        fsGroup: 1120
        runAsUser: 1120
        runAsGroup: 1120
      containers:
        - name: kiwix
          # renovate: datasource=docker depName=ghcr.io/kiwix/kiwix-serve
          image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:7431be257ac0b0b6f14633ef088774f6d5122246940b594b3017a70169058b08
          args:
            - "--verbose"
            - "--skipInvalid"
            - "/data/*.zim"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: 512Mi
      volumes:
        - name: data
          hostPath:
            path: /srv/mergerfs/union_01/kiwix
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
