---
apiVersion: v1
kind: Service
metadata:
  name: kiwix
spec:
  selector:
    app: kiwix
  ports:
    - port: 80
      targetPort: 8080
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kiwix
spec:
  hosts:
    - kiwix.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: kiwix.default.svc.cluster.local
            port:
              number: 80
