---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: servarr
    component: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: servarr
      component: sonarr
  template:
    metadata:
      labels:
        app: servarr
        component: sonarr
    spec:
      securityContext:
        fsGroup: 1121
      containers:
        - name: sonarr
          # renovate: datasource=docker depName=lscr.io/linuxserver/sonarr
          image: lscr.io/linuxserver/sonarr:4.0.17.2952-ls314@sha256:02bc962946fef994e67a38152446df25c10a52f8583aefeeb6467f9dd44cab99
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "1121"
            - name: PGID
              value: "1121"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /tv
              subPath: Shows
            - name: media
              mountPath: /downloads
              subPath: Downloads
            - name: media
              mountPath: /trash
              subPath: .trash/sonarr
          resources:
            requests:
              memory: 256Mi
      volumes:
        - name: config
          hostPath:
            path: /share/docker/sonarr
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /srv/mergerfs/union_01/media
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: servarr
    component: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: servarr
      component: radarr
  template:
    metadata:
      labels:
        app: servarr
        component: radarr
    spec:
      securityContext:
        fsGroup: 1121
      containers:
        - name: radarr
          # renovate: datasource=docker depName=lscr.io/linuxserver/radarr
          image: lscr.io/linuxserver/radarr:6.2.1.10461-ls305@sha256:4c490ccd44d31feb49dc4cc542f2148a420fc1ae0c1ba94e59b39ba4bf112716
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1121"
            - name: PGID
              value: "1121"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /movies
              subPath: Movies
            - name: media
              mountPath: /downloads
              subPath: Downloads
            - name: media
              mountPath: /trash
              subPath: .trash/radarr
          resources:
            requests:
              memory: 256Mi
      volumes:
        - name: config
          hostPath:
            path: /share/docker/radarr
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /srv/mergerfs/union_01/media
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    app: servarr
    component: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: servarr
      component: bazarr
  template:
    metadata:
      labels:
        app: servarr
        component: bazarr
    spec:
      securityContext:
        fsGroup: 1121
      containers:
        - name: bazarr
          # renovate: datasource=docker depName=lscr.io/linuxserver/bazarr
          image: lscr.io/linuxserver/bazarr:v1.5.6-ls350@sha256:4b5e510042bf471c8bafab89cada9774fba2fb25f16ec64235151cacbe847c10
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "1121"
            - name: PGID
              value: "1121"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /movies
              subPath: Movies
            - name: media
              mountPath: /tv
              subPath: Shows
            - name: media
              mountPath: /trash
              subPath: .trash/bazarr
          resources:
            requests:
              memory: 256Mi
      volumes:
        - name: config
          hostPath:
            path: /share/docker/bazarr
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /srv/mergerfs/union_01/media
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: servarr
    component: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: servarr
      component: prowlarr
  template:
    metadata:
      labels:
        app: servarr
        component: prowlarr
    spec:
      securityContext:
        fsGroup: 1121
      containers:
        - name: prowlarr
          # renovate: datasource=docker depName=lscr.io/linuxserver/prowlarr
          image: lscr.io/linuxserver/prowlarr:2.4.0.5397-ls149@sha256:a46d0ce0a8236bc4e065fe7c91a55d026c9d849620c5845250519b977d8857f3
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1121"
            - name: PGID
              value: "1121"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: 256Mi
      volumes:
        - name: config
          hostPath:
            path: /share/docker/prowlarr
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app: servarr
    component: lidarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: servarr
      component: lidarr
  template:
    metadata:
      labels:
        app: servarr
        component: lidarr
    spec:
      securityContext:
        fsGroup: 1121
      containers:
        - name: lidarr
          # renovate: datasource=docker depName=lscr.io/linuxserver/lidarr
          image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls30@sha256:b08b2194fa4ddb7f7ace9d1bfd82bd9b26f457d79aa70f42d923d2e15a820f0e
          ports:
            - containerPort: 8686
          env:
            - name: PUID
              value: "1121"
            - name: PGID
              value: "1121"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /music
              subPath: Music
            - name: media
              mountPath: /downloads
              subPath: Downloads
            - name: media
              mountPath: /trash
              subPath: .trash/lidarr
          resources:
            requests:
              memory: 256Mi
      volumes:
        - name: config
          hostPath:
            path: /share/docker/lidarr
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /srv/mergerfs/union_01/media
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: servarr
    component: flaresolverr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: servarr
      component: flaresolverr
  template:
    metadata:
      labels:
        app: servarr
        component: flaresolverr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: flaresolverr
          # renovate: datasource=docker depName=ghcr.io/flaresolverr/flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
          ports:
            - containerPort: 8191
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "America/New_York"
          resources:
            requests:
              memory: 256Mi
      nodeSelector:
        kubernetes.io/hostname: marten
