---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app: servarr
    component: sonarr
  ports:
    - port: 8989
      targetPort: 8989
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: sonarr
spec:
  hosts:
    - sonarr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: sonarr.default.svc.cluster.local
            port:
              number: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  selector:
    app: servarr
    component: radarr
  ports:
    - port: 7878
      targetPort: 7878
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: radarr
spec:
  hosts:
    - radarr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: radarr.default.svc.cluster.local
            port:
              number: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  selector:
    app: servarr
    component: bazarr
  ports:
    - port: 6767
      targetPort: 6767
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bazarr
spec:
  hosts:
    - bazarr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: bazarr.default.svc.cluster.local
            port:
              number: 6767
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app: servarr
    component: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prowlarr
spec:
  hosts:
    - prowlarr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: prowlarr.default.svc.cluster.local
            port:
              number: 9696
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  selector:
    app: servarr
    component: lidarr
  ports:
    - port: 8686
      targetPort: 8686
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: lidarr
spec:
  hosts:
    - lidarr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: lidarr.default.svc.cluster.local
            port:
              number: 8686
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: servarr
    component: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
