---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
              hostPort: 8123
          env:
            - name: TZ
              value: "America/New_York"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
          resources:
            requests:
              memory: 512Mi
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: marten
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-data
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: dbus
          hostPath:
            path: /run/dbus
            type: Directory
