---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - port: 8123
      targetPort: 8123
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: home-assistant
spec:
  hosts:
    - home.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: home-assistant.default.svc.cluster.local
            port:
              number: 8123
