---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: newt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      pod: newt
  template:
    metadata:
      labels:
        pod: newt
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - "true"
      containers:
        - name: newt
          image: fosrl/newt:1.12.5
          env:
            - name: LOG_LEVEL
              value: INFO
          envFrom:
            - secretRef:
                name: newt-secrets
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
