---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-config
data:
  DATA_DIR: "/data"
  BROWSER_WEB_URL: "http://localhost:9222"
  MEILI_ADDR: "http://localhost:7700"
  MEILI_NO_ANALYTICS: "true"
  NEXTAUTH_URL: https://kara.hydrahmlb.cc/
  OPENAI_BASE_URL: "https://openrouter.ai/api/v1"
  # Auth configs
  DISABLE_PASSWORD_AUTH: true
  DISABLE_SIGNUPS: true
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: true
  OAUTH_PROVIDER_NAME: authentik
  OAUTH_WELLKNOWN_URL: https://authentik.hydrahmlb.cc/application/o/karakeep/.well-known/openid-configuration
