---
apiVersion: v1
kind: Service
metadata:
  name: karakeep
spec:
  selector:
    app: karakeep
  ports:
    - port: 3000
      targetPort: 3000
      name: http
    - port: 3100
      targetPort: 3100
      name: mcp
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: karakeep
spec:
  hosts:
    - kara.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: karakeep.default.svc.cluster.local
            port:
              number: 3000
