# yamllint disable rule:line-length
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: trixie
    images.cnpg.io/date: "20260112"
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 13
      image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-minimal-trixie
    - major: 14
      image: ghcr.io/cloudnative-pg/postgresql:14.20-202601120807-minimal-trixie
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.15-202601120807-minimal-trixie
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.11-202601120807-minimal-trixie
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.7-202601120807-minimal-trixie
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.1-202601120807-minimal-trixie
