---
name: forgejo

networks:
  forgejo:
    name: forgejo

volumes:
  runner-data:

services:
  server:
    image: codeberg.org/forgejo/forgejo:15@sha256:55bb42bec9abef5223744804f164e37d37b20df7e8b8b4807ba213ad4f071d6d
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      - /opt/forgejo/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10101:3000"
      - "10102:22"

  runner:
    image: code.forgejo.org/forgejo/runner:12@sha256:a1a2885261a0b8337d4791dd6949651117206741ba66423c24a57c107a64d4a8
    container_name: forgejo-runner
    depends_on:
      - server
    networks:
      - forgejo
    user: "0:0"
    volumes:
      - runner-data:/data
      - ./config.yaml:/data/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "unless-stopped"
    command: "forgejo-runner daemon --config /data/config.yaml"
