[tools]
"pipx" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:yamllint" = "latest"
"pipx:ansible" = "13.2.0"
"helm" = "4.0.4"
"helm-diff" = "3.14.1"
"helmfile" = "1.2.3"

[tasks.setup]
description = "Setup environment"
depends = ["setup-ansible"]

[tasks.setup-ansible]
run = "mise exec -- ansible-galaxy install -r requirements.yml"
dir = "ansible"

[tasks.lint]
description = "Run all linters"
depends = ["lint-ansible"]

[tasks.lint-ansible]
run = [
  "mise exec -- yamllint .",
  "mise exec -- ansible-lint .",
]
dir = "ansible"

[tasks.ansible]
description = "Run an ansible playbook"
usage = '''
arg "<playbook>"
'''
run = "mise exec -- ansible-playbook playbooks/${usage_playbook}.yml"
dir = "ansible"
alias = "a"
