[tools]
"pipx" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:yamllint" = "latest"
"pipx:ansible" = "13.2.0"

[tasks.setup]
description = "Setup environment"
depends = ["setup-ansible"]

[tasks.setup-ansible]
run = "mise exec -- ansible-galaxy install -r requirements.yml"
dir = "ansible"

[tasks.lint]
description = "Run all linters"
depends = ["lint-ansible"]

[tasks.lint-ansible]
run = [
  "mise exec -- yamllint .",
  "mise exec -- ansible-lint .",
]
dir = "ansible"
