---
- name: Restart SSH
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart chrony
  ansible.builtin.service:
    name: "{{ timesync_service_name }}"
    state: restarted

- name: Save iptables rules
  ansible.builtin.command:
    cmd: netfilter-persistent save
  changed_when: true
