---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: k8up-secrets
  namespace: default
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.k8up"
