---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
data:
  PAPERLESS_URL: "https://paperless.hydrahmlb.cc"
  PAPERLESS_TIME_ZONE: "UTC"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_REDIS: "redis://paperless-redis.default.svc.cluster.local:6379"
  PAPERLESS_DBENGINE: "postgresql"
  PAPERLESS_DBHOST: "paperless-pg-rw.default.svc.cluster.local"
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: "app"
  PAPERLESS_DBUSER: "app"
  PAPERLESS_PORT: "8000"
  PAPERLESS_LOGROTATE_MAX_BACKUPS: "1"
  PAPERLESS_LOGROTATE_MAX_SIZE: "10485760"
  PAPERLESS_ENABLE_HTTP_REMOTE_USER: "false"
  PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.hydrahmlb.cc"
  # https://integrations.goauthentik.io/documentation/paperless-ngx/
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  PAPERLESS_LOGOUT_REDIRECT_URL: "https://authentik.hydrahmlb.cc/application/o/paperless/end-session/"
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
  PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
