---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 18
  storage:
    storageClass: longhorn
    size: 128Mi
