---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: paperless-redis
spec:
  podSecurityContext:
    fsGroup: 999
    runAsUser: 999
  kubernetesConfig:
    image: redis:8.8-alpine
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 512Mi
