---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: vm-prom
        uid: vm-prom
        type: prometheus
        access: proxy
        url: http://vmselect-vmcluster.monitoring.svc:8481/select/0/prometheus
        isDefault: true
        editable: false
      - name: loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc
        editable: false
      - name: tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc:3200
        editable: false
        jsonData:
          nodeGraph:
            enabled: true
