---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - configmap.yaml
  - datasources.yaml
  - secrets.yaml
  - deployment.yaml
  - deployment-mcp.yaml
  - service.yaml
