---
security_firewall_enabled: false
security_fail2ban_enabled: true
security_sysctl_hardening: true
ip_forward_enabled: true
system_timezone: UTC
system_auto_updates: false
docker_enabled: true
deploy_stacks:
  - pangolin-client

custom_groups:
  - name: runc
    gid: 1120
  - name: media
    gid: 1121
  - name: hermes
    gid: 1122

custom_users:
  - name: runc
    comment: "Rootless container user"
    uid: 1120
    group: runc
    groups: []
    shell: /sbin/nologin
    create_home: false
  - name: media
    comment: "Media and servarr user"
    uid: 1121
    group: media
    groups: []
    shell: /sbin/nologin
    create_home: false
  - name: hermes
    comment: "Hermes user"
    uid: 1122
    group: hermes
    groups: []
    shell: /bin/bash
    create_home: true
