---
security_firewall_enabled: true
security_firewall_allow_docker_subnet: true
security_firewall_rules:
  - { "comment": "HTTP", "proto": "tcp", "port": "80" }
  - { "comment": "HTTPS", "proto": "tcp", "port": "443" }
  - { "comment": "NFS", "proto": "tcp", "port": "2049" }
  - { "comment": "OMV MANAGE", "proto": "tcp", "port": "8400" }
  - { "comment": "PLEX DLNA", "proto": "udp", "port": "1900" }
  - { "comment": "PLEX DLNA SERVER", "proto": "tcp", "port": "32469" }
  - { "comment": "PLEX BONJOUR", "proto": "udp", "port": "5353" }
  - { "comment": "PLEX COMPANION", "proto": "tcp", "port": "8324" }
  - { "comment": "PLEX WEB", "proto": "tcp", "port": "32400" }
  - { "comment": "PLEX WEB", "proto": "tcp", "port": "32401" }
  - { "comment": "PLEX GDM", "proto": "udp", "port": "32410:32414" }
  - { "comment": "PLEX DISCOVERY", "proto": "tcp", "port": "41637" }
  - { "comment": "SYNCTHING", "proto": "tcp", "port": "8384" }
  - { "comment": "SYNCTHING", "proto": "tcp", "port": "22000" }
  - { "comment": "SYNCTHING", "proto": "udp", "port": "22000" }
  - { "comment": "SYNCTHING", "proto": "udp", "port": "21027" }
  - { "comment": "HOME ASSISTANT", "proto": "udp", "port": "8123" }

security_fail2ban_enabled: true
security_sysctl_hardening: true
ip_forward_enabled: true
system_timezone: UTC
system_auto_updates: false

system_extra_packages:
  - open-iscsi
  - nfs-common

system_extra_services:
  - iscsid

k3s_version: v1.35.0+k3s1
k3s_node_type: agent

k3s_node_labels:
  node-role.kubernetes.io/storage: "true"

k3s_node_taints:
  node-role.kubernetes.io/storage: "true:NoSchedule"
