---
helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: 0.15.3
    values:
      - values/metallb.yml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - resources/metallb.yml
      - events: ["preuninstall"]
        showlogs: true
        command: kubectl
        args:
          - delete
          - -f
          - resources/metallb.yml

  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    values:
      - values/traefik.yml
    needs:
      - metallb-system/metallb
