---
helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: 0.15.3
    values:
      - values/metallb.yml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - resources/metallb.yml
      - events: ["preuninstall"]
        showlogs: true
        command: kubectl
        args:
          - delete
          - -f
          - resources/metallb.yml

  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
    version: 1.28.2

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.28.2
    needs:
      - istio-base
    set:
      - name: profile
        value: ambient

  - name: istio-cni
    namespace: istio-system
    chart: istio/cni
    version: 1.28.2
    needs:
      - istio-base
    set:
      - name: profile
        value: ambient

  - name: ztunnel
    namespace: istio-system
    chart: istio/ztunnel
    version: 1.28.2
    needs:
      - istio-base

  - name: istio-ingress
    namespace: istio-ingress
    createNamespace: true
    chart: istio/gateway
    version: 1.28.2
    needs:
      - metallb-system/metallb
      - istio-system/ztunnel
