name: Mirror to GitHub

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: Push main branch to GitHub
        env:
          MIRROR_GITHUB_COM_TOKEN: ${{ secrets.MIRROR_GITHUB_COM_TOKEN }}
          MIRROR_GITHUB_COM_REPOSITORY: ${{ forgejo.repository }}
        run: |
          github_url="https://git:${MIRROR_GITHUB_COM_TOKEN}@github.com/leoxlin/${MIRROR_GITHUB_COM_REPOSITORY#*/}.git"
          git remote add github "$github_url"
          git checkout -B main origin/main
          git push --force github main
