name: Renovate

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      log_level:
        description: "Renovate log level"
        type: string
        default: info
      dry_run:
        description: "Dry run mode (full|lookup|extract|empty for off)"
        type: string
        default: ""

jobs:
  renovate:
    runs-on: docker
    container:
      image: ghcr.io/renovatebot/renovate:43@sha256:55af44f12d1d81aa6155e466ef898b63061f51a0c1e726b7f0df90f13baae8fc
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://git.hydrahmlb.dev/
          RENOVATE_AUTODISCOVER: "false"
          RENOVATE_REPOSITORIES: leoxlin/homelab
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@hydrahmlb.cc>"
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/renovate.json
          LOG_LEVEL: ${{ inputs.log_level || 'info' }}
          RENOVATE_DRY_RUN: ${{ inputs.dry_run }}
