---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  selector:
    app: overseerr
  ports:
    - port: 5055
      targetPort: 5055
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: overseerr
spec:
  hosts:
    - overseerr.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: overseerr.default.svc.cluster.local
            port:
              number: 5055
