networks:
  application:
    name: commafeed
  proxy:
    name: proxy
    external: true

services:
  commafeed:
    image: athou/commafeed:latest-postgresql
    container_name: commafeed
    user: 1000:1000
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/commafeed
      - QUARKUS_DATASOURCE_USERNAME=commafeed
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - COMMAFEED_HTTP_CLIENT_BLOCK_LOCAL_ADDRESSES=false
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commafeed.rule=Host(`rss.hydrahmlb.cc`)"

  postgresql:
    image: postgres:17
    container_name: commafeed-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: commafeed
    networks:
      - application
    volumes:
      - /share/docker/commafeed/db:/var/lib/postgresql/data
