---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: happy-server
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
