---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: happy-server-secrets
  namespace: happy-server
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.happy-server"
