networks:
  application:
    name: kavita
  proxy:
    name: proxy
    external: true

services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1121
      - PGID=1121
      - TZ=America/New_York
    volumes:
      - /share/docker/kavita/config:/config
      - /srv/mergerfs/union_01/media/Books:/data
    restart: unless-stopped
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
