networks:
  application:
    name: authentik
  proxy:
    name: proxy
    external: true

services:
  postgresql:
    container_name: authentik-db
    env_file:
      - authentik.env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /share/docker/authentik/data:/var/lib/postgresql/data
    networks:
      - application

  server:
    container_name: authentik-server
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - authentik.env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.10.2}
    ports:
      - ${COMPOSE_PORT_HTTP:-9000}
      - ${COMPOSE_PORT_HTTPS:-9443}

    restart: unless-stopped
    volumes:
      - /share/docker/authentik/media:/media
      - /share/docker/authentik/custom-templates:/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`authentik.hydrahmlb.cc`)"
      - "traefik.http.services.authentik.loadBalancer.server.port=9000"

  worker:
    container_name: authentik-worker
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - authentik.env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.10.2}
    restart: unless-stopped
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/docker/authentik/media:/media
      - /share/docker/authentik/certs:/certs
      - /share/docker/authentik/custom-templates:/templates
    networks:
      - application
