---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        fsGroup: 1121
        supplementalGroups:
          - 44   # video
          - 989  # render
      containers:
        - name: plex
          # renovate: datasource=docker depName=lscr.io/linuxserver/plex
          image: lscr.io/linuxserver/plex:1.43.2.10687-563d026ea-ls308@sha256:58f13a1df833fcb7b3499c6b52aec9d7473b93b1a1e2d2219db57e761e57903b
          ports:
            # Main web interface
            - containerPort: 32400
              hostPort: 32400
              protocol: TCP
            # Plex DLNA Server
            - containerPort: 32469
              hostPort: 32469
              protocol: TCP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
            # Plex Companion
            - containerPort: 3005
              hostPort: 3005
              protocol: TCP
            # Bonjour/Avahi discovery
            - containerPort: 5353
              hostPort: 5353
              protocol: UDP
            # GDM network discovery
            - containerPort: 32410
              hostPort: 32410
              protocol: UDP
            - containerPort: 32412
              hostPort: 32412
              protocol: UDP
            - containerPort: 32413
              hostPort: 32413
              protocol: UDP
            - containerPort: 32414
              hostPort: 32414
              protocol: UDP
          env:
            - name: PUID
              value: "1121"
            - name: PGID
              value: "1121"
            - name: TZ
              value: "America/New_York"
            - name: VERSION
              value: "latest"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /tv
              subPath: Shows
            - name: media
              mountPath: /movies
              subPath: Movies
            - name: dri
              mountPath: /dev/dri
          resources:
            requests:
              memory: 1Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          hostPath:
            path: /srv/mergerfs/union_01/media
            type: DirectoryOrCreate
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: marten
