---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-migration
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-migration
  template:
    metadata:
      labels:
        app: plex-migration
    spec:
      containers:
        - name: migration
          image: alpine:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: host-config
              mountPath: /host-config
              readOnly: true
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: host-config
          hostPath:
            path: /share/docker/plex
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: marten
