---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  selector:
    app: plex
  ports:
    - port: 32400
      targetPort: 32400
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: plex
spec:
  hosts:
    - plex.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: plex.default.svc.cluster.local
            port:
              number: 32400
