---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kagent
  namespace: kagent
spec:
  hosts:
    - kagent.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - route:
        - destination:
            host: kagent-ui.kagent.svc.cluster.local
            port:
              number: 8080
