networks:
  application:
    name: rundeck
  proxy:
    name: proxy
    external: true

services:
  rundeck:
    image: rundeck/rundeck:5.18.0
    container_name: rundeck
    links:
      - rundeck-mysql
    environment:
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: ${MYSQL_DB_PASS}
      RUNDECK_DATABASE_URL: jdbc:mysql://rundeck-mysql:3306/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_GRAILS_URL: https://rundeck.hydrahmlb.cc
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_SERVER_ADDRESS: "0.0.0.0"
      RUNDECK_SERVER_CONTEXT_PATH: "/"
      RUNDECK_GRAILS_SERVER_SESSION_COOKIE_SECURE: "false"
      RUNDECK_GRAILS_SERVER_SESSION_COOKIE_HTTP_ONLY: "true"
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rundeck.middlewares=rundeck-secure"
      - "traefik.http.middlewares.rundeck-secure.headers.sslredirect=true"
      - "traefik.http.middlewares.rundeck-secure.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.rundeck-secure.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.rundeck-secure.headers.browserXssFilter=true"
    volumes:
      - /share/docker/rundeck/libext:/home/rundeck/libext
  rundeck-mysql:
    image: mysql:5.7
    container_name: rundeck-mysql
    environment:
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=${MYSQL_DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - /share/docker/rundeck/mysql:/var/lib/mysql
    networks:
      - application
