---
all:
  hosts:
    ### Network Devices ###
    edgerouter:
      ansible_host: 192.168.2.1
    ### Named Nodes ###
    ocelot:
      ansible_host: 192.168.2.60
    marten:
      ansible_host: 192.168.2.40
    numbat:
      ansible_host: 192.168.2.50
    falcon:
      ansible_host: 46.224.223.92
    ### Control Nodes ###
    marmot-01:
      ansible_host: 192.168.2.111
    marmot-02:
      ansible_host: 192.168.2.112
    marmot-03:
      ansible_host: 192.168.2.113
    ### Worker Nodes ###
    pika-01:
      ansible_host: 192.168.2.101
    pika-02:
      ansible_host: 192.168.2.102
    pika-03:
      ansible_host: 192.168.2.103
    pika-04:
      ansible_host: 192.168.2.104

drivers:
  hosts:
    ocelot:

servers:
  hosts:
    marten:
    numbat:
    falcon:

pika:
  hosts:
    pika-[01:04]:

marmot:
  hosts:
    marmot-[01:03]:

k3s:
  hosts:
    marmot-[01:03]:
    pika-[01:04]:
    marten:

k3s_servers:
  hosts:
    marmot-[01:03]:

k3s_agents:
  hosts:
    pika-[01:04]:
    marten:
    numbat:

edgeos:
  hosts:
    edgerouter:
