---
ansible_network_os: edgeos
ansible_connection: ansible.netcommon.network_cli

edgeos_bgp_asn: 64512
edgeos_bgp_router_id: "192.168.2.1"
edgeos_bgp_peer_asn: 64513
edgeos_bgp_neighbors: []

# DNS forwarding upstreams, queried in listed order (see strict-order option).
edgeos_dns_name_servers:
  - 192.168.3.53  # AdGuard
  - 1.1.1.1       # Cloudflare fallback
