---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: server
  template:
    metadata:
      labels:
        app: prometheus
        component: server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.9.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: grafana-cloud-credentials
              mountPath: /etc/prometheus/secrets
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420
        - name: prometheus-secrets
          secret:
            secretName: prometheus-secrets
            items:
              - key: GRAFANA_CLOUD_INSTANCE
                path: username
              - key: GRAFANA_CLOUD_API_TOKEN
                path: password
