---
docker_compose_base_dir: /opt/docker/compose
docker_compose_stacks:
  - name: cloudflare-tunnel
    state: present
  - name: forgejo
    state: present
  - name: docker-registry
    state: present
    configs:
      - htpasswd.tpl
  - name: home-assistant
    state: present
  - name: newt
    state: present
