---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifecamp
  template:
    metadata:
      labels:
        app: lifecamp
    spec:
      containers:
        - name: lifecamp
          image: hydrahmlb/lifecamp:latest
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: TZ
              value: America/New_York
            - name: DB_HOST
              value: lifecamp-pg-rw.default.svc.cluster.local
            - name: DB_NAME
              value: app
            - name: DB_USER
              value: app
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lifecamp-pg-app
                  key: password
            - name: DB_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: lifecamp-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
