apiVersion: v1
kind: Service
metadata:
  name: lifecamp
spec:
  selector:
    app: lifecamp
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: lifecamp
spec:
  hosts:
    - xp.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: lifecamp.default.svc.cluster.local
            port:
              number: 5000
