---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Secret
  - ./external-secrets
  # Registry
  - ./registry-mirrors
  # Networking
  - ./metallb
  - ./istio
  - ./cert-manager
  - ./cloudflared
  - ./adguard
  - ./external-dns
  - ./static-routes
  # Storage
  - ./longhorn
  - ./longhorn-nodes
  - ./storage-marten
