---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Networking
  - ./metallb
  - ./istio
  - ./cert-manager
  - ./cloudflared
  # Storage
  - ./longhorn
  - ./longhorn-nodes
  - ./storage-marten
  # Monitoring
  - ./victoria-metrics
  - ./node-exporter
  - ./grafana
