---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: pika-01
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks: {}
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: pika-02
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks: {}
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: pika-03
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks: {}
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: pika-04
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks: {}
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: marmot-01
  namespace: longhorn-system
spec:
  disks:
    marmot-01-root:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 68719476736
      tags: []
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: marmot-02
  namespace: longhorn-system
spec:
  disks:
    marmot-01-root:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 68719476736
      tags: []
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: marmot-03
  namespace: longhorn-system
spec:
  disks:
    marmot-01-root:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 68719476736
      tags: []
