networks:
  application:
    name: writefreely
  proxy:
    name: proxy
    external: true

services:
  writefreely:
    container_name: writefreely
    restart: unless-stopped
    image: ghcr.io/writefreely/writefreely:latest
    user: root
    entrypoint: sh
    command: /go/setup.sh
    volumes:
      - /share/docker/writefreely/keys:/go/keys
      - /share/docker/writefreely/data:/go/data
      - ./template.ini:/go/deploy.ini
      - ./setup.sh:/go/setup.sh
    environment:
      - ADMIN_USER=${ADMIN_USER:-writer}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - WF_HOST=${WF_HOST:-http://localhost:8080}
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
