name: writefreely

networks:
  application:
    name: writefreely
  proxy:
    name: proxy
    external: true

services:
  writefreely:
    container_name: writefreely
    restart: unless-stopped
    image: ghcr.io/writefreely/writefreely:latest
    user: root
    entrypoint: sh -c '/go/setup.sh'
    volumes:
      - /share/docker/writefreely/keys:/go/keys
      - /share/docker/writefreely/data:/go/data
      - ./template.ini:/go/template.ini
      - ./setup.sh:/go/setup.sh
    environment:
      - WF_ADMIN_USER=${WF_ADMIN_USER:-writer}
      - WF_ADMIN_PASSWORD=${WF_ADMIN_PASSWORD:-password}
      - WF_HOST=${WF_HOST:-http://localhost:8080}
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.writefreely.rule=Host(`blog.hydrahmlb.cc`)"
      - "traefik.http.routers.writefreely.service=writefreely"
      - "traefik.http.services.writefreely.server.port=8080"
