---
- name: Ensure docker compose base directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Deploy docker compose stacks
  ansible.builtin.include_tasks: deploy.yaml
  loop: "{{ docker_compose_stacks }}"
  loop_control:
    loop_var: stack
  when: stack.state | default('present') == 'present'
