---
apiVersion: v1
kind: Namespace
metadata:
  name: database-operators
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-public-ingress
