---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: flux-build-secrets
  namespace: flux-system
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.flux-build"
