---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  releaseName: metallb
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.15.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  targetNamespace: metallb-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      logLevel: info
    speaker:
      logLevel: info
      frr:
        enabled: true
