name: downloader

networks:
  tunnel:
    name: gluetun

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /share/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS="US Massachusetts"
    restart: unless-stopped
    networks:
      - tunnel
    ports:
      - 6787:6787
      - 6788:6788
      - 6789:6789
      - 6887:6887
      - 6887:6887/udp

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - NZBGET_USER=
      - NZBGET_PASS=
    volumes:
      - /share/docker/nzbget:/config
      - /home/llin/Downloads/.staging:/staging
      - /home/llin/Downloads:/downloads
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=6788
      - TORRENTING_PORT=6887
    volumes:
      - /share/docker/qbittorrent:/config
      - /home/llin/Downloads/.staging:/staging
      - /home/llin/Downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  brave:
    image: lscr.io/linuxserver/brave:latest
    container_name: brave
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - CUSTOM_PORT=6787
      - SELKIES_SCALING_DPI=200
    volumes:
      - /share/docker/brave:/config
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    shm_size: "1gb"
    restart: unless-stopped
    runtime: nvidia
