custom_groups:
  - name: runc
    gid: 1120
  - name: media
    gid: 1121

custom_users:
  - name: runc
    uid: 1120
    group: runc
    groups: []
    comment: "Rootless container user"
    shell: /sbin/nologin
    create_home: false
  - name: media
    uid: 1121
    group: media
    groups: []
    comment: "Media and servarr user"
    shell: /sbin/nologin
    create_home: false
