---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  labels:
    app: litellm
    k8s.hydrahmlb.cc/schedule: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm-database:main-stable@sha256:8402d2372a7ba8641cf09d8fa47006088d0705979b4e87c4eb2aec58fb298ce8
          args:
            - "--config"
            - "/app/config.yaml"
          ports:
            - containerPort: 4000
              name: http
          envFrom:
            - secretRef:
                name: litellm-secrets
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-pg-app
                  key: uri
            - name: PROXY_BASE_URL
              value: https://litellm.hydrahmlb.cc
            - name: GENERIC_AUTHORIZATION_ENDPOINT
              value: https://authentik.hydrahmlb.cc/application/o/authorize/
            - name: GENERIC_TOKEN_ENDPOINT
              value: https://authentik.hydrahmlb.cc/application/o/token/
            - name: GENERIC_USERINFO_ENDPOINT
              value: https://authentik.hydrahmlb.cc/application/o/userinfo/
            - name: GENERIC_SCOPE
              value: openid profile email
            - name: GENERIC_USER_ID_ATTRIBUTE
              value: sub
            - name: GENERIC_USER_EMAIL_ATTRIBUTE
              value: email
            - name: GENERIC_USER_DISPLAY_NAME_ATTRIBUTE
              value: name
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config
