---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/application/litellm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
    - name: postgres-operator
