---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  selector:
    app: litellm
  ports:
    - port: 4000
      targetPort: 4000
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: litellm
spec:
  hosts:
    - litellm.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: litellm.default.svc.cluster.local
            port:
              number: 4000
