---
- name: Apply node labels
  when:
    - k3s_node_labels | length > 0
    - not ansible_check_mode
  ansible.builtin.command:
    cmd: >-
      k3s kubectl label node {{ inventory_hostname }}
      {% for key, value in k3s_node_labels.items() %}{{ key }}={{ value }} {% endfor %}
      --overwrite
  delegate_to: "{{ groups[k3s_server_group][0] }}"
  changed_when: true
