---
- name: Secure server nodes
  hosts: servers
  become: true
  tasks:
    # Disable root login (account lock)
    - name: Disable root account login
      ansible.builtin.user:
        name: root
        password_lock: yes
    # Disable root SSH login
    - name: Disable root SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        validate: "sshd -t -f %s"
      notify: Restart SSH
  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
      when: ansible_facts['os_family'] == "Debian"
