---
- name: Secure server nodes
  hosts: servers
  become: true
  tasks:
    - name: Disable root account login
      ansible.builtin.user:
        name: root
        password_lock: yes

    - name: Disable root SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        validate: "sshd -t -f %s"
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
      when: ansible_facts['os_family'] == "Debian"

- name: Create users
  hosts: all
  become: true
  vars_files:
    - ../vars/users.yaml
  tasks:
    - name: Create groups with configurations
      loop: "{{ custom_groups }}"
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        system: "{{ item.system | default(false) }}"
        state: present

    - name: Create users with configurations
      loop: "{{ custom_users }}"
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        groups: "{{ item.groups | default([]) | join(',') }}"
        comment: "{{ item.comment | default('') }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        create_home: "{{ item.create_home | default(true) }}"
        system: "{{ item.system | default(false) }}"
        state: present
