---
- name: Configure workstation
  hosts:
    - ocelot
  become: true
  roles:
    - role: core
      tags: role-core
    - role: semaphore
      tags: role-semaphore
    - role: traefik
      tags: role-traefik
