apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-migration
  namespace: default
  labels:
    app: immich
    component: migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
      component: migration
  template:
    metadata:
      labels:
        app: immich
        component: migration
    spec:
      containers:
        - name: migration
          image: alpine:3.21
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: immich-cache-data
              mountPath: /cache
          resources:
            requests:
              memory: 64Mi
      volumes:
        - name: immich-cache-data
          persistentVolumeClaim:
            claimName: immich-cache-data
