apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.10-0.5.3
  storage:
    storageClass: longhorn
    size: 5Gi
  postgresql:
    shared_preload_libraries:
      - vchord.so
