---
apiVersion: v1
kind: Service
metadata:
  name: matrix
spec:
  selector:
    app: matrix
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: matrix
spec:
  hosts:
    - matrix.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: matrix.default.svc.cluster.local
            port:
              number: 80
      headers:
        response:
          set:
            Strict-Transport-Security: "max-age=15552000; includeSubDomains"
