name: semaphore

networks:
  application:
    name: semaphore
  proxy:
    name: proxy
    external: true

services:
  semaphore:
    image: semaphoreui/semaphore:v2.16.47
    container_name: semaphore
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@hydrahmlb.cc
    volumes:
      - /share/docker/semaphore/data:/var/lib/semaphore
      - /share/docker/semaphore/config:/etc/semaphore
    labels:
      - "traefik.enable=true"
