---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-marten-explorer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-marten-explorer
  template:
    metadata:
      labels:
        app: storage-marten-explorer
    spec:
      containers:
        - name: explorer
          image: alpine:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: union-01-media
              mountPath: /data/media
            - name: union-01-nextcloud
              mountPath: /data/nextcloud
            - name: union-01-immich
              mountPath: /data/immich
      volumes:
        - name: union-01-media
          persistentVolumeClaim:
            claimName: marten-union-01-media
        - name: union-01-nextcloud
          persistentVolumeClaim:
            claimName: marten-union-01-nextcloud
        - name: union-01-immich
          persistentVolumeClaim:
            claimName: marten-union-01-immich
      nodeSelector:
        kubernetes.io/hostname: marten
