---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  labels:
    app: bentopdf
    k8s.hydrahmlb.cc/schedule: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bentopdf
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - name: bentopdf
          # renovate: datasource=docker depName=ghcr.io/alam00000/bentopdf-simple
          image: ghcr.io/alam00000/bentopdf-simple:latest@sha256:268f3e4a1aeed5d7035b58ab1d679da85b7c559ac3d3c08eb2177520c3647e1f
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
