---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  labels:
    app: roundcube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:1.6.x-apache
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: roundcube-config
          env:
            - name: ROUNDCUBEMAIL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roundcube-pg-app
                  key: password
          volumeMounts:
            - name: config
              mountPath: /var/www/html/config
              subPath: config
            - name: config
              mountPath: /tmp/roundcube-temp
              subPath: temp
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: roundcube-data
