---
apiVersion: v1
kind: Service
metadata:
  name: roundcube
spec:
  selector:
    app: roundcube
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: roundcube
spec:
  hosts:
    - mail.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: roundcube.default.svc.cluster.local
            port:
              number: 80
