---
apiVersion: v1
kind: Service
metadata:
  name: napdog
spec:
  selector:
    app: napdog
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 9090
      targetPort: 9090
      name: web-ui
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: napdog
spec:
  hosts:
    - napdog.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        allowHeaders:
          - "*"
        exposeHeaders:
          - "*"
        allowCredentials: true
      route:
        - destination:
            host: napdog.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: napdog-agent
spec:
  hosts:
    - napdog-agent.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        allowHeaders:
          - "*"
        exposeHeaders:
          - "*"
        allowCredentials: true
      route:
        - destination:
            host: napdog.default.svc.cluster.local
            port:
              number: 9090
