---
apiVersion: v1
kind: Service
metadata:
  name: openwebui
spec:
  selector:
    app: openwebui
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: openwebui
spec:
  hosts:
    - ai.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: openwebui.default.svc.cluster.local
            port:
              number: 8080
