---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-config
data:
  APP_ENV: "local"
  APP_URL: "https://firefly.hydrahmlb.cc"
  TRUSTED_PROXIES: "**"
  DB_CONNECTION: "pgsql"
  DB_HOST: "firefly-pg-rw.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "app"
  DB_USERNAME: "app"
  TZ: "UTC"
  DEFAULT_LANGUAGE: "en_US"
  DEFAULT_LOCALE: "equal"
