---
name: obsidian

services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest@sha256:cdb4c1381bb7d0fe17c20bc002dd8d9eef81438fda7e414a0aed896cabf98200
    container_name: obsidian
    environment:
      - PUID=1122
      - PGID=1122
      - TZ=Etc/UTC
    volumes:
      - /home/hermes/.config/obsidian:/config
      - /home/hermes/Obsidian:/data
    ports:
      - "3100:3000"
    shm_size: 1gb
    restart: unless-stopped
