---
name: obsidian

services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1122
      - PGID=1122
      - TZ=Etc/UTC
    volumes:
      - /home/hermes/.config/obsidian:/config
      - /home/hermes/Obsidian:/data
    ports:
      - "3100:3000"
    shm_size: 1gb
    restart: unless-stopped
