---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: goose-secrets
  namespace: goose
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.goose"
