---
apiVersion: v1
kind: Service
metadata:
  name: goose
spec:
  selector:
    app: goose
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: goose
spec:
  hosts:
    - goose.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: goose.goose.svc.cluster.local
            port:
              number: 3000
