---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-pg
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 17
  storage:
    storageClass: longhorn
    size: 1Gi
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: n8n-redis
spec:
  podSecurityContext:
    fsGroup: 999
    runAsUser: 999
  kubernetesConfig:
    image: redis:alpine3.22
    resources:
      requests:
        memory: 64Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 256Mi
