name: utask

networks:
  application:
    name: utask
  proxy:
    name: proxy
    external: true

services:
  utask-db:
    container_name: utask-db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: utask
      POSTGRES_USER: utask
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /share/docker/utask/data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utask"]
      interval: 10s
      timeout: 5s
      retries: 5

  utask:
    container_name: utask
    image: ovhcom/utask:v1.33.3
    environment:
      DEBUG: "true"
      CONFIGURATION_FROM: "env:CFG"
      CFG_DATABASE: "postgres://utask:${POSTGRES_PASSWORD}@utask-db/utask?sslmode=disable"
      CFG_UTASK_CFG: |
        {
          "admin_usernames":["admin"],
          "application_name":"µTask"
        }
      CFG_CALLBACK_CONFIG: '{"base_url": "https://utask.hydrahmlb.cc"}'
      CFG_ENCRYPTION_KEY: '{"identifier":"storage","cipher":"aes-gcm","timestamp":1535627466,"key":"e5f45aef9f072e91f735547be63f3434e6de49695b178e3868b23b0e32269800"}'
    volumes:
      - ../../utask/functions:/app/functions:ro
      - ../../utask/templates:/app/templates:ro
      - ../../utask/scripts:/app/scripts:ro
    depends_on:
      utask-db:
        condition: service_healthy
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
