---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: kimi-ocelot
  namespace: istio-ingress
spec:
  hosts:
    - kimi.hydrahmlb.cc
  location: MESH_EXTERNAL
  ports:
    - number: 52000
      name: http
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: 192.168.2.60
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kimi
  namespace: istio-ingress
spec:
  hosts:
    - kimi.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: kimi.hydrahmlb.cc
            port:
              number: 52000
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: hermes-ocelot
  namespace: istio-ingress
spec:
  hosts:
    - hermes.hydrahmlb.cc
  location: MESH_EXTERNAL
  ports:
    - number: 52000
      name: http
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: 192.168.2.60
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hermes
  namespace: istio-ingress
spec:
  hosts:
    - hermes.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: hermes.hydrahmlb.cc
            port:
              number: 52000
