networks:
  application:
    name: syncthing
    driver: bridge
  proxy:
    name: proxy
    external: true

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1120
      - PGID=1120
      - TZ=Etc/New_York
    volumes:
      - /share/docker/syncthing/config:/config
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - application
      - proxy
    labels:
      - "traefik.enable=true"
