---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik
  - ./fetcherr
  - ./immich
  - ./k8up
  - ./karakeep
  - ./nextcloud
  - ./plex
  - ./servarr
  - ./tubearchivist
