---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik
  - ./bentopdf
  - ./calibre
  - ./commafeed
  - ./fetcherr
  - ./immich
  - ./k8up
  - ./karakeep
  - ./kiwix
  - ./nextcloud
  - ./openwebui
  - ./overseerr
  - ./plex
  - ./rsshub
  - ./servarr
  - ./tubearchivist
