---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik
  # - ./oauth2-proxy
  - ./rsshub
  - ./commafeed
  - ./n8n
  - ./karakeep
  - ./openwebui
  - ./tubearchivist
  - ./plex
  - ./nextcloud
  - ./home-assistant
