---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: hermes
spec:
  hosts:
    - hermes.junco.local
  location: MESH_EXTERNAL
  ports:
    - number: 8642
      name: api
      protocol: HTTP
    - number: 9119
      name: dashboard
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: 192.168.4.11
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hermes
spec:
  hosts:
    - hermes.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - match:
        - uri:
            prefix: /v1
      route:
        - destination:
            host: hermes.junco.local
            port:
              number: 8642
    - route:
        - destination:
            host: hermes.junco.local
            port:
              number: 9119
