[servers]
marten ansible_host=192.168.2.40

[local]
ocelot ansible_connection=local ansible_become_password_prompt=yes

[servers:vars]
ansible_user=hydra
ansible_ssh_private_key_file=/home/llin/.ssh/agent_ed25519
ansible_ssh_pass_prompt=yes

[all:vars]
ansible_become=yes
ansible_become_method=sudo
