---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - system/system.yaml
  - infrastructure/infrastructure.yaml
  - infrastructure/pangolin-newt/pangolin-newt.yaml
  - database/mongodb-operator/mongodb-operator.yaml
  - database/postgres-operator/postgres-operator.yaml
  - database/redis-operator/redis-operator.yaml
  - application/authentik/authentik.yaml
  - application/bentopdf/bentopdf.yaml
  - application/calibre/calibre.yaml
  - application/cloud-code/cloud-code.yaml
  - application/collabora/collabora.yaml
  - application/commafeed/commafeed.yaml
  - application/fetcherr/fetcherr.yaml
  - application/grafana/grafana.yaml
  - application/hermes/hermes.yaml
  - application/immich/immich.yaml
  - application/k8up/k8up.yaml
  - application/kagent/kagent.yaml
  - application/karakeep/karakeep.yaml
  - application/kiwix/kiwix.yaml
  - application/litellm/litellm.yaml
  - application/matrix/matrix.yaml
  - application/nextcloud/nextcloud.yaml
  - application/node-exporter/node-exporter.yaml
  - application/obsidian/obsidian.yaml
  - application/openwebui/openwebui.yaml
  - application/openshell/openshell.yaml
  - application/overseerr/overseerr.yaml
  - application/paperless/paperless.yaml
  - application/plex/plex.yaml
  - application/rsshub/rsshub.yaml
  - application/servarr/servarr.yaml
  - application/singularr/singularr-app.yaml
  - application/tdarr/tdarr.yaml
  - application/tubearchivist/tubearchivist.yaml
  - application/victoria-metrics/victoria-metrics.yaml
patches:
  - path: ./patches/prefer-worker.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=worker
  - path: ./patches/prefer-server.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=server
  - path: ./patches/prefer-storage.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=storage
