---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - system.yaml
  - infrastructure.yaml
  - database.yaml
  - application.yaml
patches:
  - path: patches/prefer-worker.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=worker
  - path: patches/prefer-server.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=server
  - path: patches/prefer-storage.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=storage
