---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - system.yaml
  - crds.yaml
  - infrastructure.yaml
  - database.yaml
  - application.yaml
  - application/paperless.yaml
  - application/matrix.yaml
  - application/commafeed.yaml
  - application/bentopdf.yaml
  - application/calibre.yaml
  - application/collabora.yaml
  - application/kiwix.yaml
  - application/openwebui.yaml
  - application/overseerr.yaml
  - application/rsshub.yaml
  - application/fetcherr.yaml
  - application/k8up.yaml
  - application/nextcloud.yaml
  - application/plex.yaml
  - application/servarr.yaml
  - application/tubearchivist.yaml
patches:
  - path: ./patches/prefer-worker.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=worker
  - path: ./patches/prefer-server.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=server
  - path: ./patches/prefer-storage.yaml
    target:
      kind: Deployment
      labelSelector: k8s.hydrahmlb.cc/schedule=storage
