---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: adguard-secrets
  namespace: adguard
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.adguard"
