---
- name: Start configure
  ansible.netcommon.cli_command:
    command: "configure"

- name: Configure BGP router ID
  ansible.netcommon.cli_command:
    command: "set protocols bgp {{ edgeos_bgp_asn }} parameters router-id {{ edgeos_bgp_router_id }}"

- name: Configure BGP neighbors
  ansible.netcommon.cli_command:
    command: "set protocols bgp {{ edgeos_bgp_asn }} neighbor {{ item }} remote-as {{ edgeos_bgp_peer_asn }}"
  loop: "{{ edgeos_bgp_neighbors }}"

- name: Commit config
  ansible.netcommon.cli_command:
    command: "commit"

- name: Save config
  ansible.netcommon.cli_command:
    command: "save"
