networks:
  application:
    name: vikunja
  proxy:
    name: proxy
    external: true

services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    restart: unless-stopped
    environment:
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_SERVICE_PUBLICURL: https://todo.hydrahmlb.cc/
      # Note the default path is /app/vikunja/vikunja.db.
      # This config variable moves it to a different folder so you can use a volume and
      # store the database file outside the container so state is persisted even if the container is destroyed.
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
    volumes:
      - /share/docker/vikunja/files:/app/vikunja/files
      - /share/docker/vikunja/db:/db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(`todo.hydrahmlb.cc`)"
