---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: newt-secrets-marten
  namespace: pangolin-newt
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.newt.marten"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: newt-secrets-marmot-01
  namespace: pangolin-newt
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.newt.marmot-01"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: newt-secrets-marmot-02
  namespace: pangolin-newt
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.newt.marmot-02"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: newt-secrets-marmot-03
  namespace: pangolin-newt
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.newt.marmot-03"
