---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: obsidian
spec:
  hosts:
    - obsidian.junco.local
  location: MESH_EXTERNAL
  ports:
    - number: 3100
      name: http
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: 192.168.4.11
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: obsidian
spec:
  hosts:
    - obsidian.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: obsidian.junco.local
            port:
              number: 3100
