---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: marten
      tolerations:
        - key: node-role.kubernetes.io/storage
          operator: Equal
          value: "true"
          effect: NoSchedule
