---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflared-secrets
  namespace: istio-public-ingress
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Hydra/items/main.cloudflared"
