---
apiVersion: v1
kind: Service
metadata:
  name: cloud-code
spec:
  selector:
    app: cloud-code
  ports:
    - port: 80
      targetPort: 3001
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: cloud-code
spec:
  hosts:
    - code.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: cloud-code.default.svc.cluster.local
            port:
              number: 80
