---
apiVersion: v1
kind: Service
metadata:
  name: affine
spec:
  selector:
    app: affine
  ports:
    - port: 3010
      targetPort: 3010
      name: http
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: affine
spec:
  hosts:
    - affine.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
    - istio-public-ingress/hydrahmlb-public-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: affine.default.svc.cluster.local
            port:
              number: 3010
