---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tubearchivist-config
data:
  HOST_UID: "1121"
  HOST_GID: "1121"
  ES_URL: "http://tubearchivist-es.default.svc.cluster.local:9200"
  REDIS_CON: "redis://tubearchivist-redis.default.svc.cluster.local:6379"
  TA_HOST: "https://tubearchivist.hydrahmlb.cc"
  TA_USERNAME: "admin"
  TZ: "UTC"
  TA_LOGIN_AUTH_MODE: "local"
  TA_AUTH_PROXY_USERNAME_HEADER: "REMOTE_USER"
