---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tubearchivist
  labels:
    app: tubearchivist
    k8s.hydrahmlb.cc/schedule: storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tubearchivist
  template:
    metadata:
      labels:
        app: tubearchivist
    spec:
      securityContext:
        fsGroup: 1121
      containers:
        - name: tubearchivist
          # renovate: datasource=docker depName=bbilly1/tubearchivist
          image: bbilly1/tubearchivist:v0.5.10@sha256:dfe723cf008520e1758ecc3e59e6ea8761dd10d5bb099cd87289e80f5bd66567
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: tubearchivist-config
            - secretRef:
                name: tubearchivist-secrets
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: media
              mountPath: /youtube
              subPath: YouTube
          resources:
            requests:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: tubearchivist-cache
        - name: media
          hostPath:
            path: /srv/mergerfs/union_01/media
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: marten
