---
apiVersion: v1
kind: Pod
metadata:
  name: tubearchivist-migration
  namespace: default
  labels:
    app: tubearchivist-migration
    k8s.hydrahmlb.cc/schedule: storage
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 1121
  containers:
    - name: migration
      image: alpine:3.21
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: cache
          mountPath: /dest/cache
        - name: es-data
          mountPath: /dest/es-data
      resources:
        requests:
          memory: 256Mi
  volumes:
    - name: cache
      persistentVolumeClaim:
        claimName: tubearchivist-cache
    - name: es-data
      persistentVolumeClaim:
        claimName: tubearchivist-es
