---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: tubearchivist-redis
spec:
  podSecurityContext:
    fsGroup: 999
    runAsUser: 999
  kubernetesConfig:
    image: redis:8-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    resources:
      requests:
        memory: 64Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 128Mi
