---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: langflow
  namespace: default
spec:
  hosts:
    - langflow.hydrahmlb.cc
  gateways:
    - istio-ingress/hydrahmlb-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 301
    - route:
        - destination:
            host: langflow-service.default.svc.cluster.local
            port:
              number: 8080
